askme/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^ask$', views.ask, name='ask'),
    url(r'^hot$', views.hot, name='hot'),
    url(r'^signin$', views.signin, name='signin'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^question/(?P<question_id>\d+)$', views.question, name='question'),
    url(r'^settings$', views.settings, name='settings'),
    url(r'^signup$', views.signup, name='signup'),
    url(r'^tag/(?P<tag>\w+)$', views.tag, name='tag'),
    url(r'^$', views.index, name='index'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('askme.urls')),
]

askme/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms



class QuestionManager(models.Manager):
    def recent(self):
        return self.order_by('-creation_date')

    def hot(self):
        return self.order_by('-rating')


class Tag(models.Model):
    content = models.CharField(primary_key=True, max_length=10)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return '/tag/%s' % self.content

class Profile(models.Model):
    user = models.OneToOneField(User)
    avatar = models.FileField()
    rating = models.IntegerField()
    reg_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nickname

class Question(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    rating = models.IntegerField()
    creation_date = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    objects = QuestionManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return 'question/%d' % self.id

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    content = models.TextField()
    is_correct = models.BooleanField()
    rating = models.IntegerField()
    creation_date = models.DateTimeField(auto_now_add=True)

class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        widgets = { 'content': forms.Textarea(attrs={'class' : 'form-control'})}

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']
        widgets = { 'content': forms.FileInput(attrs={'class' : 'form-control'})}

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username' , 'email', 'password' ]
        widgets = {
          'username': forms.TextInput(attrs={'class' : 'form-control'}),
          'password': forms.PasswordInput(attrs={'class' : 'form-control'}),
          'email': forms.EmailInput(attrs={'class' : 'form-control'})
        }

templates/ask.html
{% extends "./base.html" %}

{% block header %}
  <h1>New question</h1>
{% endblock %}

{% block content %}
  <form class="form-horizontal">
    <div class="form-group">
      <label class="col-sm-2 control-label">Title</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" maxlength="140">
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Text</label>
      <div class="col-sm-10">
        <textarea class="form-control" rows="10"></textarea>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Tags</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" maxlength="140">
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">ASK!</button>
      </div>
    </div>
  </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>AskNikolay</title>

    <!-- Bootstrap -->
    {% load static %}
    <link href="{% static './css/bootstrap.min.css' %}" rel="stylesheet">
    {% load static %}
    <link href="{% static './css/askme.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'index' %}">AskNikolay</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-primary">ASK!</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li>
              <img src="/uploads/{{ user.profile.avatar.name }}" class="img-rounded navbar-brand">
            </li>
            <li>
              <p class="navbar-text">{{ user.username }}</p>
            </li>
            <li><a href="{% url 'settings' %}">settings</a></li>
            <li><a href="{% url 'logout' %}">log out</a></li>
          {% else %}
            <li><a href="{% url 'signin' %}">log in</a></li>
            <li><a href="{% url 'signup' %}">register</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <main class="container">
    <div class="row">
      <div class="col-sm-offset-1 col-sm-8">
        <header class="page-header">
          {% block header %}
          {% endblock %}
        </header>
        <section>
          {% block content %}
          {% endblock %}
        </section>
      </div>

      <aside class="col-sm-offset-1 col-sm-2">
        <div class="panel panel-default">
          <div class="panel-heading"><h3 class="panel-title">Popular Tags</h3></div>
          <div class="panel-body">
            {% for t in toptags %}
              <a href="{% url 'tag' 'bender' %}">{% lorem 1 w random %}</a>
            {% endfor %}
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Best Members</h3>
          </div>
          <ul class="list-group">
            {% for u in topusers %}
              <li class="list-group-item text-capitalize">{% lorem 1 w random %}</li>
            {% endfor %}
          </ul>
        </div>
      </aside>
    </div>
  </main>

  <footer class="footer">
    <p class="text-muted">Технопарк ©2018</p>
  </footer>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  {% load static %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  {% load static %}
  <script src="{% static 'js/papper.min.js' %}"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  {% load static %}
  <script src="{% static './js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/index.html
{% extends './base.html' %}

{% block header %}
  <h1>
    {% if header == 'index' %}
      New questions
      <small><a href="{% url 'hot' %}">Hot questions</a></small>
    {% elif header == 'hot' %}
      Hot questions
      <small><a href="{% url 'index' %}">New questions</a></small>
    {% elif header == 'tag' %}
      Tagged questions
      <small>{{ tag }}</small>
    {% endif %}
  </h1>
{% endblock %}

{% block content %}
  <div class="list-group">
    {% for q in questions %}
      <div class="row list-group-item">
        <div class="col-sm-2">
          <img src="/uploads/{{ q.author.avatar.name }}" class="img-responsive img-rounded">
          <br>
          <input type="number" class="form-control" value="{{ q.rating }}">
        </div>
        <div class="col-sm-10">
          <h4 class="list-group-item-heading">
            <a href="{% url 'question' q.id %}">
              {{ q.title }} <small>{{ q.author.user.username }}</small>
            </a>
          </h4>
          <p class="list-group-item-text">
            {{ q.content }}<br>
            {% lorem 1 b random %}
          </p>
          <br>
          <div class="row">
            <p class="col-sm-3">
              <a href="{% url 'question' q.id %}">
                answers ({{ q.answer_set.count }})
              </a>
            </p>
            <p class="col-sm-9">
              Tags:
              {% for t in q.taglist %}
                <a href="{% url 'tag' t.content %}">
                  {{ t.content }}
                </a>
              {% endfor %}
            </p>
          </div>
        </div>
      </div>
    {% endfor %}

    {% include './paginator.html' with objects=questions %}
  </div>
{% endblock %}

<!-- <html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Askme</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/askme.css">
</head>
<body>
    <header>
    
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">AskServer</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        </div>
    </nav>
    </header>

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-2">
                        <img src="img/loren.jpeg" alt="123">
                    </div>
                    <div class="col-md-10">
                        <h3>My brend new header</h3>
                        <p>кашмаааааааааааааааааааар</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">dddd</div>
        </div>
    </div>

    <main role="main" class="container">
    <h1 class="mt-5">Sticky footer with fixed navbar</h1>
    <p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added with <code>padding-top: 60px;</code> on the <code>body &gt; .container</code>.</p>
    <p>Back to <a href="../sticky-footer">the default sticky footer</a> minus the navbar.</p>
    </main>

    <footer class="footer">
    <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
    </div>
    </footer>

    <script src="js/jquery.min.js"></script>
    <script src="js/papper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>
</html> -->

templates/paginator.html
<nav aria-label="Page navigation">
  <ul class="pagination">
    {% if objects.has_previous %}
      <li>
        <a href="?page={{ objects.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% endif %}

    {% for n in objects.paginator.page_range %}
      <li {% if objects.number == n %}class="active"{% endif %}>
        <a href="?page={{ n }}">
          {{ n }}
        </a>
      </li>
    {% endfor %}

    {% if objects.has_next %}
      <li>
        <a href="?page={{ objects.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>

templates/question.html
{% extends "./base.html" %}

{% block header %}
  <div class="row">
    <div class="col-sm-3">
      {% load static %}
      <img src="/uploads/{{ question.author.avatar.name}}" class="img-responsive img-rounded">
      <br>
      <input type="number" class="form-control" value="{{ question.rating }}">
    </div>
    <div class="col-sm-9">
      <h3>{{ question.title}}</h3>
      {% lorem 2 p random %}
      <p>
        Tags:
        {% for t in question.taglist %}
          <a href="{% url 'tag' t.content %}">{{ t.content }}</a>
        {% endfor %}
      </p>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="list-group">
    {% include './paginator.html' with objects=answers %}

    {% for a in answers %}
      <div class="row list-group-item">
        <div class="col-sm-2 ">
          <img src="/uploads/{{ a.author.avatar.name}}" class="img-responsive img-rounded">
          <br>
          <input type="number" class="form-control" value="{{ a.rating }}">
        </div>

        <div class="col-sm-10">
          <small>{{ a.id }}</small>
          <p class="list-group-item-text">
            {{ a.content }}<br>
            {% lorem 1 b random %}
          </p>

          <div class="checkbox">
            <label>
              <input type="checkbox" {% if a.is_correct %}checked{% endif %}> Correct!
            </label>
          </div>
        </div>
      </div>
    {% endfor %}

    {% include './paginator.html' with objects=answers %}

    {% if user.is_authenticated %}
      <form action="{% url 'question' question.id %}" method="post" class="row">
        {% csrf_token %}
        {% if form.non_field_errors %}
          <div class="row">
            <div class="alert alert-danger">{{ form.non_field_errors }}</div>
          </div>
        {% endif %}

        {% for field in form %}
          <div class="form-group">
            {{ field.errors }}
            {{ field }}
            {% if field.help_text %}
              <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
          </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">
          Answer
        </button>
      </form>
    {% endif %}
  </div>
{% endblock %}

templates/settings.html
{% extends "./base.html" %}

{% block header %}
  <h1>Settings: {{ user.username }}</h1>
{% endblock %}

{% block content %}
<form method="post" action="{% url 'settings' %}" enctype="multipart/form-data" class="form-horizontal">
  {% csrf_token %}
  {% if userform.non_field_errors %}
    <div class="row">
      <div class="col-sm-offset-4 col-sm-4">
        <div class="alert alert-danger">{{ userform.non_field_errors }}</div>
      </div>
    </div>
  {% endif %}
  {% for field in userform %}
    {% if field.errors %}
      <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
          <div class="alert alert-danger">{{ field.errors }}</div>
        </div>
      </div>
    {% endif %}
    
    <div class="form-group">
      <label class="col-sm-4 control-label">
        {{ field.label }}
      </label>
      <div class="col-sm-4">
        {{ field }}
      </div>
      {% if field.help_text %}
        <div class="col-sm-4">
          <p class="form-control-static">{{ field.help_text|safe }}</p>
        </div>
      {% endif %}
    </div>
  {% endfor %}
  
  {% if passupdateform.non_field_errors %}
    <div class="row">
      <div class="col-sm-offset-4 col-sm-4">
        <div class="alert alert-danger">{{ passupdateform.non_field_errors }}</div>
      </div>
    </div>
  {% endif %}
  {% for field in passupdateform %}
    {% if field.errors %}
      <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
          <div class="alert alert-danger">{{ field.errors }}</div>
        </div>
      </div>
    {% endif %}
    
    <div class="form-group">
      <label class="col-sm-4 control-label">
        {{ field.label }}
      </label>
      <div class="col-sm-4">
        {{ field }}
      </div>
      {% if field.help_text %}
        <div class="col-sm-4">
          <p class="form-control-static">{{ field.help_text|safe }}</p>
        </div>
      {% endif %}
    </div>
  {% endfor %}
  
  {% if profileform.non_field_errors %}
    <div class="row">
      <div class="alert alert-danger">{{ profileform.non_field_errors }}</div>
    </div>
  {% endif %}
  {% for field in profileform %}
    {% if field.errors %}
      <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
          <div class="alert alert-danger">{{ field.errors }}</div>
        </div>
      </div>
    {% endif %}
    
    <div class="form-group">
      <label class="col-sm-4 control-label">
        {{ field.label }}
      </label>
      <div class="col-sm-4">
        {{ field }}
      </div>
      {% if field.help_text %}
        <div class="col-sm-4">
          <p class="form-control-static">{{ field.help_text|safe }}</p>
        </div>
      {% endif %}
    </div>
  {% endfor %}
  
  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-4">
      <img src="/uploads/{{ user.profile.avatar.name }}" class="img-responsive img-thumbnail" >
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-10">
      <button type="submit" class="btn btn-default">Save</button>
    </div>
  </div>
</form>
{% endblock %}

templates/signin.html
{% extends "./base.html" %}

{% block header %}
  <h1>Log In</h1>
{% endblock %}

{% block userblock %}
  {% include "./userblock_anon.html" %}
{% endblock %}

{% block content %}
  <form action="{% url 'login' %}" method="post" class="form-horizontal">
    {% csrf_token %}
    {% if form.non_field_errors %}
      <div class="row">
        <div class="alert alert-danger">{{ form.non_field_errors }}</div>
      </div>
    {% endif %}
    
    {% for field in form %}
      <div class="form-group">
        {{ field.errors }}
        <label class="col-sm-4 control-label">
          {{ field.label }}
        </label>
        <div class="col-sm-4">
          {{ field }}
        </div>
        {% if field.help_text %}
          <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
      </div>
    {% endfor %}
    
    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-10">
        <button type="submit" class="btn btn-default">Log in!</button>
      </div>
    </div>
    
    <input name="continue" type="hidden" value="{{ location }}">
  </form>
  
  <div class="col-sm-offset-4 col-sm-10"><a href="{% url 'signup' %}">create new account</a></div>
{% endblock %}

templates/signup.html
{% extends "./base.html" %}

{% block header %}
  <h1>Registration</h1>
{% endblock %}

{% block content %}
<form action="{% url 'signup' %}" method="post" class="form-horizontal">
  {% csrf_token %}
  {% if form.non_field_errors %}
    <div class="row">
      <div class="col-sm-offset-4 col-sm-4">
        <div class="alert alert-danger">{{ form.non_field_errors }}</div>
      </div>
    </div>
  {% endif %}
  {% for field in form %}
    {% if field.errors %}
      <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
          <div class="alert alert-danger">{{ field.errors }}</div>
        </div>
      </div>
    {% endif %}
    
    <div class="form-group">
      <label class="col-sm-4 control-label">
        {{ field.label }}
      </label>
      <div class="col-sm-4">
        {{ field }}
      </div>
      {% if field.help_text %}
        <div class="col-sm-4">
          <p class="form-control-static">{{ field.help_text|safe }}</p>
        </div>
      {% endif %}
    </div>
  {% endfor %}
  
  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-10">
      <button type="submit" class="btn btn-default">Register!</button>
    </div>
  </div>
</form>
{% endblock %}